package modelo;
// Generated 2 dic. 2019 23:08:30 by Hibernate Tools 5.4.7.Final

/**
 * TAccesos generated by hbm2java
 */
public class TAccesos implements java.io.Serializable {

	private int codAcceso;
	private TEstaciones TEstaciones;
	private String descripcion;

	public TAccesos() {
	}

	public TAccesos(int codAcceso, TEstaciones TEstaciones, String descripcion) {
		this.codAcceso = codAcceso;
		this.TEstaciones = TEstaciones;
		this.descripcion = descripcion;
	}

	public int getCodAcceso() {
		return this.codAcceso;
	}

	public void setCodAcceso(int codAcceso) {
		this.codAcceso = codAcceso;
	}

	public TEstaciones getTEstaciones() {
		return this.TEstaciones;
	}

	public void setTEstaciones(TEstaciones TEstaciones) {
		this.TEstaciones = TEstaciones;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
