package hibernate_metro;
// Generated 2 dic. 2019 23:08:30 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TCocheras generated by hbm2java
 */
public class TCocheras implements java.io.Serializable {

	private int codCochera;
	private String nombre;
	private String direccion;
	private Set TTreneses = new HashSet(0);

	public TCocheras() {
	}

	public TCocheras(int codCochera, String nombre, String direccion) {
		this.codCochera = codCochera;
		this.nombre = nombre;
		this.direccion = direccion;
	}

	public TCocheras(int codCochera, String nombre, String direccion, Set TTreneses) {
		this.codCochera = codCochera;
		this.nombre = nombre;
		this.direccion = direccion;
		this.TTreneses = TTreneses;
	}

	public int getCodCochera() {
		return this.codCochera;
	}

	public void setCodCochera(int codCochera) {
		this.codCochera = codCochera;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set getTTreneses() {
		return this.TTreneses;
	}

	public void setTTreneses(Set TTreneses) {
		this.TTreneses = TTreneses;
	}

}
